# Generated by Django 3.0 on 2021-01-12 12:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wd', '0003_order_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='saction_to',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'США'), (2, 'Китай')], max_length=3, null=True, verbose_name='Страны для санкции'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rockets_to',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Вашингтон'), (2, 'Нью Йорк'), (3, 'Чикаго'), (4, 'Лас Вегас'), (5, 'Пекин'), (6, 'Шанхай'), (7, 'Гуанчжоу'), (8, 'Гонконг')], max_length=15, null=True, verbose_name='Города под прицелом'),
        ),
    ]
