# Generated by Django 3.0 on 2021-01-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wd', '0004_auto_20210112_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя Раунда'),
        ),
    ]
