# Generated by Django 3.0 on 2021-01-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wd', '0005_round_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buy_rockets',
            field=models.IntegerField(blank=True, default=0, max_length=1, null=True, verbose_name='покупка ракетт'),
        ),
    ]
