# Generated by Django 3.0 on 2021-01-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wd', '0006_auto_20210113_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buy_rockets',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='покупка ракетт'),
        ),
    ]
