# Generated by Django 3.0 on 2021-01-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wd', '0008_auto_20210113_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rockets_to',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Города под прицелом'),
        ),
        migrations.AlterField(
            model_name='order',
            name='saction_to',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Страны для санкции'),
        ),
    ]
