# Generated by Django 3.0 on 2021-01-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wd', '0009_auto_20210113_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость приказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='build_tech',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='кач ядерки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='eco_up',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Улучшение экологии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shield_for_city_1',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='щит на город1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shield_for_city_2',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='щит на город2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shield_for_city_3',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='щит на город3'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shield_for_city_4',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='щит на город4'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_for_city_1',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='статус на город1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_for_city_2',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='статус на город2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_for_city_3',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='статус на город3'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_for_city_4',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='статус на город4'),
        ),
    ]
