# Generated by Django 3.0 on 2021-01-14 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wd', '0010_auto_20210114_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата отправки приказа'),
        ),
    ]
