# Generated by Django 3.0 on 2021-01-14 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wd', '0011_order_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки приказа'),
        ),
    ]
