# Generated by Django 3.0 on 2021-01-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wd', '0012_auto_20210114_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ecology',
        ),
        migrations.AddField(
            model_name='round',
            name='ecology',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Экология'),
        ),
    ]
