# Generated by Django 3.1.5 on 2021-01-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wd', '0013_auto_20210114_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('message', models.CharField(blank=True, max_length=30, null=True)),
                ('start_seconds', models.IntegerField(blank=True, null=True, verbose_name='start_seconds')),
                ('seconds_elapsed', models.IntegerField(blank=True, null=True, verbose_name='seconds_elapsed')),
                ('seconds_remaining', models.IntegerField(blank=True, null=True, verbose_name='seconds_remaining')),
            ],
        ),
    ]
