# Generated by Django 3.1.5 on 2021-01-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wd', '0014_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gametimer', to='wd.game'),
        ),
    ]
